Areas/Admin/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class PermissionsController : Controller
    {
        private readonly Ctx _ctx;
        
        public PermissionsController(Ctx ctx)
        {
            _ctx = ctx;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            return View(await _ctx.Permissions.ToListAsync());
        }
        
        public async Task<IActionResult> Details(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Permission permission)
        {
            if (ModelState.IsValid)
            {
                await _ctx.Permissions.AddAsync(permission);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(permission);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Permission permission)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(permission);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(permission);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            _ctx.Permissions.Remove(permission);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPermissionToRole(PermissionViewModel model)
        {
            Role role = await _ctx.Roles.Include(pr => pr.PermissionRole).ThenInclude(p => p.Permission).FirstAsync(r => r.RoleId == model.RoleId);
            Permission permission = await _ctx.Permissions
                .FirstOrDefaultAsync(p => p.PermissionId == Convert.ToInt32(model.Permission));

            if (!role.PermissionRole.Exists(p => p.Permission == permission))
            {
                var result = new PermissionRole()
                {
                    Permission = permission,
                    PermissionId = permission.PermissionId,
                    Role = role,
                    RoleId = model.RoleId
                };
                
                role.PermissionRole.Add(result);
                _ctx.Update(role);
                await _ctx.SaveChangesAsync();
            }

            return RedirectToAction("Edit", "Roles", new { id = model.RoleId});
        }

        public async Task<IActionResult> AddAllPermissionsToRole(string roleId)
        {
            var permissions = await _ctx.Permissions.ToListAsync();
            var rolePermissions = await _ctx.Roles.Include(pr => pr.PermissionRole)
                .ThenInclude(p => p.Permission)
                .FirstAsync(r => r.RoleId == roleId);
            
           
            foreach (var permission in permissions)
            {
                if (rolePermissions.PermissionRole.Exists(p => p.Permission == permission)) continue;
                var temp = new PermissionRole()
                {
                    Permission = permission,
                    PermissionId = permission.PermissionId,
                    Role = rolePermissions,
                    RoleId = rolePermissions.RoleId
                };
                rolePermissions.PermissionRole.Add(temp);
            }

            await _ctx.SaveChangesAsync();

            return RedirectToAction("Edit", "Roles", new { id = roleId});
        }

        public async Task<IActionResult> DeletePermissionFromRole(string roleId, int permissionId)
        {
            var role = await _ctx.Roles.Include(pr => pr.PermissionRole).ThenInclude(p => p.Permission)
                .FirstAsync(r => r.RoleId == roleId);
            var perm = role.PermissionRole.FirstOrDefault(p => p.PermissionId == permissionId);
            
            role.PermissionRole.Remove(perm);
            await _ctx.SaveChangesAsync();
            
            return RedirectToAction("Edit", "Roles", new { id = roleId});
        }
    }
}

Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class RolesController : Controller
    {
        private readonly Ctx _ctx;
        
        public RolesController(Ctx ctx)
        {
            _ctx = ctx;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var roles = await _ctx.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Role role)
        {
            if (ModelState.IsValid)
            {
               await _ctx.Roles.AddAsync(role);
               await _ctx.SaveChangesAsync();
               return RedirectToAction("Index");
            }

            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(role);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _ctx.Roles.FindAsync(id);
            _ctx.Roles.Remove(role);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(RoleViewModel model)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == model.UserId);
            var role = await _ctx.Roles.FirstOrDefaultAsync(r => r.RoleId == model.Role);

            if (user.RoleUser.Exists(r => r.RoleId == model.Role))
                return RedirectToAction("Edit", "Users", new {id = model.UserId});
            
            var newRole = new RoleUser()
            {
                Role = role,
                RoleId = model.Role,
                UserId = model.UserId,
                User = user
            };
            user.RoleUser.Add(newRole);
            _ctx.Update(user);
            await _ctx.SaveChangesAsync();

            return RedirectToAction("Edit", "Users", new {id = model.UserId});
        }

        public async Task<IActionResult> DeleteUserFromRole(int id, string roleId)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == id);
            var role = user.RoleUser.FirstOrDefault(r => r.RoleId == roleId);

            user.RoleUser.Remove(role);
            await _ctx.SaveChangesAsync();
            
            return RedirectToAction("Edit", "Users", new {id = id});
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EVE.SingleSignOn.Core;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RoleBasedAccessControl.Models;
using RoleBasedAccessControl.Models.Settings;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoleBasedAccessControl.Controllers
{
    public class LoginController : Controller
    {
        private readonly SsoConfig _ssoConfig;
        private readonly ISingleSignOnClient _sso;
        private readonly Ctx _db;

        public LoginController(IOptions<SsoConfig> ssoConfig, Ctx db)
        {
            _db = db;
            _ssoConfig = ssoConfig.Value;
            _sso = new SingleSignOnClient(GetEveSettings());
        }

        private SsoSettings GetEveSettings()
        {
            var settings = new SsoSettings()
            {
                BaseUrl = _ssoConfig.BaseUrl,
                CallbackUrl = _ssoConfig.CallbackUrl,
                ClientId = _ssoConfig.ClientId,
                ClientSecret = _ssoConfig.ClientSecret,
                ContactEmail = _ssoConfig.ContactEmail,
                Scope = _ssoConfig.Scope,
                State = Guid.NewGuid().ToString()
            };

            return settings;
        }


        public IActionResult Login()
        {
            if (!User.Identity.IsAuthenticated)
                return Redirect(_sso.GetAuthenticationUrl());

            return RedirectToAction("About", "Home");
        }

        public async Task<IActionResult> Callback(string code, string state)
        {
            // Authenticate using the code we received from SSO
            // so let's get some tokens
            var tokens = await _sso.AuthenticateAsync(code);

            // Store the tokens in session
            var character = await _sso.VerifyAsync(tokens.AccessToken);

            // Save the character if they are not already in the DB
            var user = await _db.Users.FirstOrDefaultAsync(u => u.CharacterOwnerHash == character.CharacterOwnerHash);

            if (user == null)
            {
                var newUser = new User()
                {
                    CharacterOwnerHash = character.CharacterOwnerHash,
                    CharacterId = character.CharacterId,
                    CharacterName = character.CharacterName,
                    LockoutEnabled = false,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };

                // Add a standard user role
                var roles = await _db.Roles.ToListAsync();
                var roleUser = new List<RoleUser>();
                var ru = new RoleUser()
                {
                    User = newUser,
                    UserId = newUser.UserId,
                    Role = roles.FirstOrDefault(role => role.IsDefaultRole == true),
                    RoleId = roles.FirstOrDefault(role => role.IsDefaultRole == true)?.RoleId
                };
                roleUser.Add(ru);
                newUser.RoleUser = roleUser;

                await _db.Users.AddAsync(newUser);
                await _db.SaveChangesAsync();
            }

            // Get any roles the user may have
            var userRole = _db.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role).First(u => u.CharacterOwnerHash == character.CharacterOwnerHash);

            // Add claims
            var claims = new List<Claim>
            {
                new Claim("roles", JsonConvert.SerializeObject(userRole,
                        new JsonSerializerSettings()
                        {
                            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                        })),
                new Claim(ClaimTypes.NameIdentifier, character.CharacterOwnerHash),
                new Claim(ClaimTypes.Name, character.CharacterName),
                new Claim(ClaimTypes.SerialNumber, character.CharacterId.ToString()),
                new Claim(ClaimTypes.UserData, JsonConvert.SerializeObject(character)),
                new Claim("tokens", JsonConvert.SerializeObject(tokens)),
                new Claim("tokenExpiry", JsonConvert.SerializeObject(DateTime.UtcNow.AddSeconds(tokens.ExpiresIn))),
                new Claim("canRefresh", JsonConvert.SerializeObject(!string.IsNullOrEmpty(tokens.RefreshToken)))
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);

            // Sign User in
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                            claimsPrinciple,
                                            new AuthenticationProperties
                                            {
                                                IsPersistent = true
                                            });


            return RedirectToAction("About", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Layout.cshtml
@using RoleBasedAccessControl.Policies
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoleBasedAccessControl</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RoleBasedAccessControl</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @{
                        if ((await AuthorizationService.AuthorizeAsync(User, new RequiredRole(){Role = "Human Resources"}, "DynamicMenu")).Succeeded)
                        {
                            <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                        }
                        if ((await AuthorizationService.AuthorizeAsync(User, new RequiredRole(){Role = "Admin"}, "DynamicMenu")).Succeeded)
                        {
                            <li><a asp-area="Admin" asp-controller="Roles" asp-action="Index">Roles</a></li>
                            <li><a asp-area="Admin" asp-controller="Permissions" asp-action="Index">Permissions</a></li>
                        }
                        if ((await AuthorizationService.AuthorizeAsync(User,  "IsSysAdmin")).Succeeded)
                        {
                            <li><a href="#">Super Secret Menu</a></li>
                        }
                        if (User.Identity.IsAuthenticated)
                        {
                            <li><a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Login" asp-action="Login">Login</a></li>
                        }
                    }
                    
                    
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RoleBasedAccessControl</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>