Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RoleBasedAccessControl.Models
{
    public class User
    {
        public User()
        {
            UpdatedAt = DateTime.Now;
        }

        [Key]
        public long UserId { get; set; }
        [Display(Name = "Character Owner Hash")]
        public string CharacterOwnerHash { get; set; }
        [Display(Name = "Character ID")]
        public long CharacterId { get; set; }
        [Display(Name = "CharacterName")]
        public string CharacterName { get; set; }
        [Display(Name = "Lockout")]
        public bool LockoutEnabled { get; set; }
        [Display(Name = "Created At")]
        [DataType(DataType.Date)]
        public DateTime CreatedAt { get; set; }
        [Display(Name = "Last Updated")]
        [DataType(DataType.Date)]
        public DateTime UpdatedAt { get; set; }

        public List<RoleUser> RoleUser { get; set; }
    }
}

Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class RolesController : Controller
    {
        private readonly Ctx _ctx;
        
        public RolesController(Ctx ctx)
        {
            _ctx = ctx;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var roles = await _ctx.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Role role)
        {
            if (ModelState.IsValid)
            {
               await _ctx.Roles.AddAsync(role);
               await _ctx.SaveChangesAsync();
               return RedirectToAction("Index");
            }

            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(role);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _ctx.Roles.FindAsync(id);
            _ctx.Roles.Remove(role);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(RoleViewModel model)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == model.UserId);
            var role = await _ctx.Roles.FirstOrDefaultAsync(r => r.RoleId == model.Role);

            if (user.RoleUser.Exists(r => r.RoleId == model.Role))
                return RedirectToAction("Edit", "Users", new {id = model.UserId});
            
            var newRole = new RoleUser()
            {
                Role = role,
                RoleId = model.Role,
                UserId = model.UserId,
                User = user
            };
            user.RoleUser.Add(newRole);
            _ctx.Update(user);
            await _ctx.SaveChangesAsync();

            return RedirectToAction("Edit", "Users", new {id = model.UserId});
        }

        public async Task<IActionResult> DeleteUserFromRole(int id, string roleId)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == id);
            var role = user.RoleUser.FirstOrDefault(r => r.RoleId == roleId);

            user.RoleUser.Remove(role);
            await _ctx.SaveChangesAsync();
            
            return RedirectToAction("Edit", "Users", new {id = id});
        }
    }
}

Areas/Admin/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class UsersController : Controller
    {
        private readonly Ctx _ctx;
        
        public UsersController(Ctx ctx)
        {
            _ctx = ctx;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var users = await _ctx.Users.ToListAsync();
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }
            var user = await _ctx.Users.FirstOrDefaultAsync(u => u.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(User user)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(user);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return BadRequest();
            }
            var user = await _ctx.Users.FirstOrDefaultAsync(u => u.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _ctx.Users.FirstOrDefaultAsync(u => u.UserId == id);
            _ctx.Users.Remove(user);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/ViewComponents/AddRoleToUserViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.ViewComponents
{
    public class AddRoleToUserViewComponent : ViewComponent
    {
        private readonly Ctx _ctx;

        public AddRoleToUserViewComponent(Ctx ctx)
        {
            _ctx = ctx;
        }

        public async Task<IViewComponentResult> InvokeAsync(long id)
        {
            var roles = await _ctx.Roles.ToListAsync();
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == id);
            
            var unusedRoles = new List<SelectListItem>();
            foreach (var role in roles)
            {
                if (user.RoleUser.Exists(r => r.Role == role)) continue;
                
                var temp = new SelectListItem()
                {
                    Value = role.RoleId,
                    Text = role.Name
                };
                
                unusedRoles.Add(temp);
            }
            
            
            var result = new RoleViewModel()
            {
                Roles = unusedRoles,
                UserId = id
            };

            return View(result);
        }
    }
}

Areas/Admin/Views/Users/Delete.cshtml
@model RoleBasedAccessControl.Models.User
@{
    Layout = "_Layout";
    ViewBag.Title = "Delete Role";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Role</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterOwnerHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterOwnerHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Admin/Views/Users/Details.cshtml
@model RoleBasedAccessControl.Models.User

@{
    ViewBag.Title = "Role Details";
    Layout = "_Layout";
}

<div>
    <h4>Role Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterOwnerHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterOwnerHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CharacterId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/Users/Edit.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Http.Features.Authentication
@model RoleBasedAccessControl.Models.User
@inject IAuthorizationService AuthorizationService
@{
    Layout = "_Layout";
    ViewBag.Title = "Edit User";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Role</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharacterId)
        @Html.HiddenFor(model => model.CharacterOwnerHash)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.CreatedAt)
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(model => model.CharacterName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CharacterName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CharacterName, "", new { @class = "text-danger" })
                </div>
            </div>

            @* <div class="form-group"> *@
            @*     @Html.LabelFor(model => model., htmlAttributes: new { @class = "control-label col-md-2" }) *@
            @*     <div class="col-md-4"> *@
            @*         @Html.EditorFor(model => model.RoleDescription, new { htmlAttributes = new { @class = "form-control" } }) *@
            @*         @Html.ValidationMessageFor(model => model.RoleDescription, "", new { @class = "text-danger" }) *@
            @*     </div> *@
            @* </div> *@

            <div class="form-group">
                @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.LockoutEnabled)
                        @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}

<h4>Roles Associated with this User</h4>
@{
    if ((await AuthorizationService.AuthorizeAsync(User, "DynamicPermissions")).Succeeded)
    {
        if (Model.RoleUser == null)
        {
            <h4><font color="red">No Associated Roles...</font></h4>
            <br/>
        }
        else
        {
            <table id="PermissionTable" style="width: 65%">
                <thead>
                <th style="width: 90%">
                    Permission
                </th>
                <th>
                    Action
                </th>
                </thead>
                @foreach (var role in Model.RoleUser.OrderBy(n => n.Role.Name))
                {
                    <tr>
                        <td>
                            @Html.ActionLink(role.Role.Name, "Details", "Roles", new {id = role.RoleId})
                        </td>
                        <td>
                            <center>
                                <a class="text-danger" href="@Url.Action("DeleteUserFromRole", "Roles", new {id = Model.UserId, roleId = role.RoleId})" class="deletePermission" id=@Model.UserId permissionid=@role.RoleId>
                                    Remove
                                </a>
                            </center>
                        </td>
                    </tr>
                }
            </table>
            <br/>
        }
        <div>@await Component.InvokeAsync("AddRoleToUser", new {id = Model.UserId})</div>
        <br />
    }
    else
    {
        <h4 class="text-danger">You do not have the permissions to edit user roles.</h4>
    }
}


<div>
    @Html.ActionLink("Back to List", "Index") | @Html.ActionLink("Go to Roles", "Index", "Roles")
</div>

Areas/Admin/Views/Users/Index.cshtml
@model IEnumerable<RoleBasedAccessControl.Models.User>

@{
    ViewBag.Title = "Users";
    Layout = "_Layout";
}

<h2>Users</h2>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CharacterName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CharacterName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
                @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
            </td>
        </tr>
    }

</table>