Models/Role.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RoleBasedAccessControl.Models
{
    public class Role
    {
        [Key]
        public string RoleId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(75)]
        [Display(Name = "Description")]
        public string RoleDescription { get; set; }
        public bool IsSysAdmin { get; set; }
        public bool IsDefaultRole { get; set; }

        public List<RoleUser> RoleUser { get; set; }
        public List<PermissionRole> PermissionRole { get; set; }
    }
    
    public class RoleViewModel
    {
        public string Role { get; set; }
        public List<SelectListItem> Roles { get; set; }
        public long UserId { get; set; }
    }

    public class RequiredRole
    {
        public string Role { get; set; }
    }
}

Areas/Admin/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class PermissionsController : Controller
    {
        private readonly Ctx _ctx;
        
        public PermissionsController(Ctx ctx)
        {
            _ctx = ctx;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            return View(await _ctx.Permissions.ToListAsync());
        }
        
        public async Task<IActionResult> Details(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Permission permission)
        {
            if (ModelState.IsValid)
            {
                await _ctx.Permissions.AddAsync(permission);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(permission);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Permission permission)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(permission);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(permission);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            if (permission == null)
            {
                return NotFound();
            }
            return View(permission);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var permission = await _ctx.Permissions.FindAsync(id);
            _ctx.Permissions.Remove(permission);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPermissionToRole(PermissionViewModel model)
        {
            Role role = await _ctx.Roles.Include(pr => pr.PermissionRole).ThenInclude(p => p.Permission).FirstAsync(r => r.RoleId == model.RoleId);
            Permission permission = await _ctx.Permissions
                .FirstOrDefaultAsync(p => p.PermissionId == Convert.ToInt32(model.Permission));

            if (!role.PermissionRole.Exists(p => p.Permission == permission))
            {
                var result = new PermissionRole()
                {
                    Permission = permission,
                    PermissionId = permission.PermissionId,
                    Role = role,
                    RoleId = model.RoleId
                };
                
                role.PermissionRole.Add(result);
                _ctx.Update(role);
                await _ctx.SaveChangesAsync();
            }

            return RedirectToAction("Edit", "Roles", new { id = model.RoleId});
        }

        public async Task<IActionResult> AddAllPermissionsToRole(string roleId)
        {
            var permissions = await _ctx.Permissions.ToListAsync();
            var rolePermissions = await _ctx.Roles.Include(pr => pr.PermissionRole)
                .ThenInclude(p => p.Permission)
                .FirstAsync(r => r.RoleId == roleId);
            
           
            foreach (var permission in permissions)
            {
                if (rolePermissions.PermissionRole.Exists(p => p.Permission == permission)) continue;
                var temp = new PermissionRole()
                {
                    Permission = permission,
                    PermissionId = permission.PermissionId,
                    Role = rolePermissions,
                    RoleId = rolePermissions.RoleId
                };
                rolePermissions.PermissionRole.Add(temp);
            }

            await _ctx.SaveChangesAsync();

            return RedirectToAction("Edit", "Roles", new { id = roleId});
        }

        public async Task<IActionResult> DeletePermissionFromRole(string roleId, int permissionId)
        {
            var role = await _ctx.Roles.Include(pr => pr.PermissionRole).ThenInclude(p => p.Permission)
                .FirstAsync(r => r.RoleId == roleId);
            var perm = role.PermissionRole.FirstOrDefault(p => p.PermissionId == permissionId);
            
            role.PermissionRole.Remove(perm);
            await _ctx.SaveChangesAsync();
            
            return RedirectToAction("Edit", "Roles", new { id = roleId});
        }
    }
}

Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RoleBasedAccessControl.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "DynamicPermissions")]
    public class RolesController : Controller
    {
        private readonly Ctx _ctx;
        
        public RolesController(Ctx ctx)
        {
            _ctx = ctx;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var roles = await _ctx.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Role role)
        {
            if (ModelState.IsValid)
            {
               await _ctx.Roles.AddAsync(role);
               await _ctx.SaveChangesAsync();
               return RedirectToAction("Index");
            }

            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                _ctx.Update(role);
                await _ctx.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var role = await _ctx.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _ctx.Roles.FindAsync(id);
            _ctx.Roles.Remove(role);
            await _ctx.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(RoleViewModel model)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == model.UserId);
            var role = await _ctx.Roles.FirstOrDefaultAsync(r => r.RoleId == model.Role);

            if (user.RoleUser.Exists(r => r.RoleId == model.Role))
                return RedirectToAction("Edit", "Users", new {id = model.UserId});
            
            var newRole = new RoleUser()
            {
                Role = role,
                RoleId = model.Role,
                UserId = model.UserId,
                User = user
            };
            user.RoleUser.Add(newRole);
            _ctx.Update(user);
            await _ctx.SaveChangesAsync();

            return RedirectToAction("Edit", "Users", new {id = model.UserId});
        }

        public async Task<IActionResult> DeleteUserFromRole(int id, string roleId)
        {
            var user = await _ctx.Users.Include(ru => ru.RoleUser).ThenInclude(r => r.Role)
                .FirstOrDefaultAsync(u => u.UserId == id);
            var role = user.RoleUser.FirstOrDefault(r => r.RoleId == roleId);

            user.RoleUser.Remove(role);
            await _ctx.SaveChangesAsync();
            
            return RedirectToAction("Edit", "Users", new {id = id});
        }
    }
}

Areas/Admin/ViewComponents/AddPermissionsToRoleViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.ViewComponents
{
    public class AddPermissionsToRoleViewComponent : ViewComponent
    {
        private readonly Ctx _ctx;

        public AddPermissionsToRoleViewComponent(Ctx ctx)
        {
            _ctx = ctx;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id)
        {
            var permissions = await _ctx.Permissions.ToListAsync();
            var rolePermissions = await _ctx.Roles.Include(pr => pr.PermissionRole)
                .ThenInclude(p => p.Permission)
                .FirstAsync(r => r.RoleId == id);
            
            var unusedPermissions = new List<SelectListItem>();
            foreach (var permission in permissions)
            {
                if (rolePermissions.PermissionRole.Exists(p => p.Permission == permission)) continue;
                var temp = new SelectListItem()
                {
                    Value = permission.PermissionId.ToString(),
                    Text = permission.PermissionDescription
                };
                unusedPermissions.Add(temp);
            }

            var result = new PermissionViewModel()
            {
                Permissions = unusedPermissions,
                RoleId = id
            };
            
            return View(result);
        }
    }
}

Areas/Admin/ViewComponents/ListPermissionsViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoleBasedAccessControl.Models;

namespace RoleBasedAccessControl.Areas.Admin.ViewComponents
{
    public class ListPermissionsViewComponent : ViewComponent
    {
        private readonly Ctx _ctx;

        public ListPermissionsViewComponent(Ctx ctx)
        {
            _ctx = ctx;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id)
        {
            var role = await GetRoleAsync(id);

            return View(role);
        }

        private Task<Role> GetRoleAsync(string id)
        {
            return _ctx.Roles.Include(pr => pr.PermissionRole).ThenInclude(p => p.Permission).FirstAsync(r => r.RoleId == id);
        }
    }
}

Areas/Admin/Views/Roles/Create.cshtml
@model RoleBasedAccessControl.Models.Role
@{
    Layout = "_Layout";
    ViewBag.Title = "Create Role";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create Role</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSysAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSysAdmin)
                    @Html.ValidationMessageFor(model => model.IsSysAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Admin/Views/Roles/Delete.cshtml
@model RoleBasedAccessControl.Models.Role
@{
    Layout = "_Layout";
    ViewBag.Title = "Delete Role";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Role</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSysAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSysAdmin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Admin/Views/Roles/Details.cshtml
@model RoleBasedAccessControl.Models.Role

@{
    ViewBag.Title = "Role Details";
    Layout = "_Layout";
}

<div>
    <h4>Role Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSysAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSysAdmin)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RoleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/Roles/Edit.cshtml
@model RoleBasedAccessControl.Models.Role
@{
    Layout = "_Layout";
    ViewBag.Title = "Edit Role";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Role</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RoleId)
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RoleDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.RoleDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoleDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsSysAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsSysAdmin)
                        @Html.ValidationMessageFor(model => model.IsSysAdmin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}

    <h4>Permissions Associated with this Role</h4>
    <div>@await Component.InvokeAsync("ListPermissions", new {id = Model.RoleId})</div>
    <div>@await Component.InvokeAsync("AddPermissionsToRole", new {id = Model.RoleId})</div>
    <br />

<div>
    @Html.ActionLink("Back to List", "Index") | @Html.ActionLink("Go to Permissions", "Index", "Permissions")
</div>

Areas/Admin/Views/Roles/Index.cshtml
@model IEnumerable<RoleBasedAccessControl.Models.Role>
@{
    Layout = "_Layout";
    ViewBag.Title = "Roles";
}

<h2>Roles</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsSysAdmin)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsSysAdmin)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.RoleId }) |
                @Html.ActionLink("Details", "Details", new { id=item.RoleId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.RoleId })
            </td>
        </tr>
    }

</table>